### PR TITLE
Remove unnecessary startup log message

### PR DESCRIPTION
**Pull request by vera-akulenko**

### CODE REVIEW

**Comment by ellieayla** [comment]
`YOUR_NEW_NAME`? Did you intend to make that configurable? I don't think the tests would pass as-is either - are you still working on this?

**Comment by vera-akulenko** [comment]
> `YOUR_NEW_NAME`? Did you intend to make that configurable? I don't think the tests would pass as-is either - are you still working on this?

yes, I am still working

**Comment by vera-akulenko** [comment]
@ellieayla  Could you approve my pull request?

**Comment by ellieayla** [comment]
You squashed the commits to just a9f90d98c4f089dd3957c4c4cb724a888b7415da removing a log message? Is that intentional?

**Comment by vera-akulenko** [comment]
yes It is intentional

**Comment by max-ch-88** [comment]
Hello @ellieayla
Could you tell me when the updated version will be published on https://rubygems.org/gems/logstash-codec-loginsight?

**Comment by ellieayla** [comment]
Sorry for the delay; this is the first release since maintainer changed. Published to https://rubygems.org/gems/logstash-codec-loginsight/versions/0.1.50

Manual unless someone wants to automate: #2.

**Comment by max-ch-88** [comment]
Thank you very much )
Maybe you will add the v0.1.50 tag as well?
there https://github.com/ellieayla/logstash-codec-loginsight/tags

**Pull request merged**
